### ISSUE TITLE
Maintenance before next work

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/hummingbird#117]
### Global modifications
- [x] Remove all old boostrap 4 (and 3) classes which are not used any more. WIP here: https://github.com/PrestaShop/theme-refacto/issues/115
- [x] Refactor/improve/unify layouts - full width, limited width, limited with left column, limited with right column, limited with both columns. The structure must be the same. We should remove the excessive wrappers. We should have one `container` making the padding. I already prepared limiting classes for pages like login.
- [x] Remove all hardcoded image sizes, if set. Check that all images have the width and height attributes dynamically loaded from the image thumbnail size.
- [x] Remove as much floats as we can. Check for `position: absolute;` and other dangerous behavior, if not needed, remove it.
- [ ] Check all recent fixes and changes in classic and reimplement them here.
- [ ] Check that no block from classic was removed. 

### Order confirmation
- [ ] Use order-detail-no-return.tpl instead of order-confirmation-table.tpl, why have two tables.
- [ ] Distribute the hooks evenly on the page. There is no point in having all thre down there. And payment return hook should be right on the top, it's important that customer knows if the payment went through!

### Add all necessary hooks
Ask community and provide all blocks needed.
 Ask community and provide all hooks needed.

- [ ] https://github.com/PrestaShop/PrestaShop/issues/24319
- [ ] https://github.com/PrestaShop/PrestaShop/issues/26223 - Developers want to append similar hooks (for comparing for example) as wishlist for other actions. In 1.6, there was hookDisplayProductListFunctionalButtons, we should bring it back.
- [ ] https://github.com/PrestaShop/PrestaShop/issues/26608
- [ ] https://github.com/PrestaShop/PrestaShop/issues/26800 - Hook before payment confirmation button, so we can display additional data in checkout, additional optional consents etc.
- [ ] Hook for extra lines in cart totals, so cashondelivery (and other modules) can display the extra charges for selecting this payment method and don't have to do it with JS.
