### ISSUE TITLE
[EPIC] Build the new theme

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/hummingbird#2]
Here is the list of the task needed to create the new theme of PS 8.0

[Figma link for mockups](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=0%3A1)

### Home page
- [x] #37
- [x] #40
- [x] #41
- [x] #43 
- [x] #45
- [x] #55
- [x] #56

### Product page
- [x] #3 
- [x] #6 
- [x] #33
- [x] #45
- [x] #55 
- [x] #56

### Category page
- [x] #45 
- [x] #55
- [x] #47 
- [x] #49
- [x] #56

### Cart page
- [x] #51
- [x] #56

### Checkout page
- [x] #5
- [x] #8 
- [x] #9 
- [x] #10 
- [x] #11

### Sign in page
- [x] #17

### My account page
- [x] #19 
- [x] #20  
- [x] #21
- [x] #22  
- [x] #23 
- [ ] #24 

### Manufacturer, Store, Sitemap, and Contact us pages
- [x] #70
- [x] #85 
- [x] #83 
- [x] #91 

### Components
- [x] #53
- [x] #45
- [x] #55
- [x] #56
- [x] #60

---

### Home page
- [x] #38 
- [x] #39 
- [x] #42 
- [x] #44 
- [x] #46
- [x] #57

### Product page
- [x] #4 
- [x] #7  
- [x] #32 
- [x] #46
- [x] #57

### Category page
- [x] #46 
- [x] #48 
- [x] #50
- [x] #57

### Cart page
- [x] #52
- [x] #57

### Checkout page
- [x] #12
- [x] #13 
- [x] #14 
- [x] #15 
- [x] #16 

### Sign in page
- [x] #18

### My account page
- [x] #25 
- [x] #26  
- [x] #27 
- [x] #28  
- [x] #29  
- [x] #30 

### Manufacturer, Store, Sitemap, and Contact us pages
- [x] #90 
- [x] #86
- [x] #84
- [x] #92

### Components
- [x] #54
- [x] #46
- [x] #57
- [x] #58
- [x] #61

**Comment by NeOMakinG** [comment]
Hello everyone,

Here is a list of common feedbacks we received from the community, we need to try to reduce these pains as much as possible, so when someone takes an issue, please try to think about it:

- Bootstrap 5
- Good structure inside `src` directory, which was `_dev` before
- No more core.js file, everything in the theme (with an exported library organised as services in order to achieve some API calls)
- Lazyloading everywhere
- Good CSS/classes names, BEM-like. Product list is a good example if you want to collapses to it
- Use a reused variable for the first part of every component classes, in smarty AND inside scss, so we're able to rename it easily.
- JSON-LD
- Think about adding hooks, because it looks like some are missing
- Try to make it as clean as possible with only bootstrap 5, then integrate the custom mods inside the custom folder, so it's easy to remove and looks clean without custom styles
- Don't add unneeded dependencies, bootstrap should almost be enough for everything such as sliders and other components
- If you working on JS, don't use jQuery, we will keep it for retrocompatibility with some modules but we won't use it as JavaScript is enough now.
- We should try to get rid of these API reloading some markup content, if you face this problem, please create an issue so we'll try to negotiate some endpoints in order to go further
- Add as much event as possible on JS important features, so theme and module developers are able to play with these events
- Try to use as much bootstrap components as possible.
- Get rid of JQuery UI
- If you develop a custom component (such as product list, small product for example), please create his own files/scss sheets, and reuse it instead of repeating code.


Here is how the theme looks for the moment, before Scott reworked a lof of mockups:

![image](https://user-images.githubusercontent.com/14963751/136391070-8803679e-a644-4576-883a-2a39c8ef0e3c.png)
![image](https://user-images.githubusercontent.com/14963751/136391134-27ef9dca-5597-4bac-9b90-74365c30da77.png)
![image](https://user-images.githubusercontent.com/14963751/136391195-5ed5e585-c1a2-4866-8798-2f6e238f5b65.png)
![image](https://user-images.githubusercontent.com/14963751/136391236-b619385b-1b22-4c62-a0c6-cccc3906b018.png)
![image](https://user-images.githubusercontent.com/14963751/136391289-e9d07b0f-24c5-4385-ba38-40b8a6048ae2.png)
![image](https://user-images.githubusercontent.com/14963751/136391430-561eaf82-c027-45d0-a4ba-51b3935d0522.png)


# And if you remove custom styles, you've a raw bootstrap 5 theme structure
![image](https://user-images.githubusercontent.com/14963751/136391599-81ac7761-33de-4db1-84c2-3535f206470f.png)
![image](https://user-images.githubusercontent.com/14963751/136391636-56ec9068-699b-4705-a7b9-566db25fe8cf.png)
![image](https://user-images.githubusercontent.com/14963751/136391663-c5df46f7-3a39-4b7c-879f-34850f68c535.png)
![image](https://user-images.githubusercontent.com/14963751/136391703-9cac2cea-559c-4367-9129-2d2e0168c4c4.png)

**Comment by PrestaEdit** [comment]
It's seems that somes are missing as:

- Sitemap
- Contact us 
- Store page

Also inside the account, the kind of module as blockwishlist (Don't know if it will be shipped again and if the theme need to handle it or it's the module itself, there).

**Comment by Hlavtox** [comment]
### Current workflow
- [ ] Build everything in an initial phase to 95% completion
- [ ] Do major cleanup of code
- [ ] Recheck everything and polish everything to be exactly to the mockup. Discuss inconsitencies.
- [ ] Check with community and discuss what level of "basic" they want the theme to look like with custom styles removed.
- [ ] Then, remove as much code from "core" to "custom" until it breaks.
- [ ] Check that we didn't remove any modding capabilities. Add some if possible.

cc @NeOMakinG
