### ISSUE TITLE
EPIC TODO

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/hummingbird#218]
### General ideas to explore and check
- Find a way to build module specific styles into separate CSS files. We don't want to include everything in the main theme.css, when some users won't use half of these styles and scripts.
- We need to check that styles belong to core/custom properly. When building the theme without custom scss, we should get a solid pure boostrap base.
- Perform cleaning and optimization regularily, simplify to the maximum.
- We need to backport all classic theme fixes implemeted since we started building this.
_______________________________

### Bugs and things missing

**Product page**
- [x] Finish availability in classic and hummingbird - https://github.com/PrestaShop/PrestaShop/pull/25062 and https://github.com/PrestaShop/PrestaShop/pull/27759 - It doesn't use the specified labels at all for out of stock products for example.
- [x] Style other prices like unit prices and ecotax and others.
- [ ] Add more prices to theme array so its available and put some sense to it. - https://github.com/PrestaShop/PrestaShop/issues/28039

**Images**
- [x] Implement image system - https://github.com/PrestaShop/PrestaShop/issues/27318

**Checkout**
- [x] displayCarrierExtraContent hook is working, but is not appearing and disappearing dynamically, only on page load
- [x] Linklist module is using footer template in left column.

**Category**
- [x] Desktop nouislider not working after resizing the screen and opening and closing mobile filters
- [x] Style category left column module
- [ ] Prepare hidden component for listing pagination and show all button, for theme developers. 🔴 ResultsPerPage parameter should support something like "all", one could set it to 9999, but that smells.
- [ ] Prepare hidden support for add to cart button **that works and doesn't have bugs.**
- [ ] Prepare hidden support for showing short description on product list. Small font, with removed HTML tags and truncated.
- [ ] Mobile filters - put green OK button that closes the sidebar to the bottom, so the user can have one more way to go outside.
- [x] Search suggestions in empty category do not work, only in header.
- [x] Page jumping to the top after selecting filters.
- [x] After selecting some filters, products in category are 1 column on display < 1200px.
- [ ] Price filter - wrong format of numbers. No space between thousands and `.` instead of `,` for decimal places. OK in active filters section.

**My account**
- [x] What about this issue? https://github.com/PrestaShop/PrestaShop/issues/26849 🔴 **NEED DEV POWER** ping @matks

**General**
- [x] IDEA - **YML configuration options for every theme** - Something like wordpress theme customizer. Every merchant could then easily customize the theme colors etc. It would contain a a set of options for the theme, without any configuration modules that are usually shipped with the theme. It could contain dropdowns, radios, inputs etc. Prestashop would load it dynamically load them from the YML, present them and provide saving their values. 🔴 **NEED DEV POWER** 🔴 **NEED PRODUCT TEAM**
- [x] Module for homepage content - banners/categories/texts/etc - some kind of visual builder. Banner module is obsolete - 1 image in 2022? Nooooo. 🔴 **NEED DEV POWER** 🔴 **NEED PRODUCT TEAM**
- [x] Think about unifying the order summary table on confirmation and tracking page.

**Comment by matks** [comment]
>  IDEA - YML configuration options for every theme - Something like wordpress theme customizer. Every merchant could then easily customize the theme colors etc. It would contain a a set of options for every theme - dropdowns, radios, inputs etc. Prestashop would load it dynamically load and present them from the YML. 🔴 NEED DEV POWER 🔴 NEED PRODUCT TEAM

This would be done in the Core if I am not wrong. Else no other theme will follow.

> Every merchant could then easily customize the theme colors etc.

Please lower your expectations :p we can build it but we cannot force theme developers to apply it

> What about this issue? https://github.com/PrestaShop/PrestaShop/issues/26849 🔴 

I added a suggestion inside the issue to make some progress. I think it should be something pretty simple :)

**Comment by Hlavtox** [comment]
> Please lower your expectations :p we can build it but we cannot force theme developers to apply it

Wrong wording, of course :D

**Comment by mparvazi** [comment]
Product image thumbnails are not carousal, so we have over-height in modal view even for on-line thumbnails.

**Comment by mparvazi** [comment]
@Hlavtox 

The config rules in theme.yml must be converted to a css file (e.g. override.css)
But the styling rules have been implemented by scss, so it would be error prone.

Currently we have this problem in RTL for BO. The rules for fixing RTL issues are in css (theme.rtlfix) but BO theme styled by scss.

I mean, something like this makes it harder for theme maintainability.

**Comment by amaury-hanser** [comment]
> IDEA - YML configuration options for every theme - Something like wordpress theme customizer. Every merchant could then easily customize the theme colors etc. It would contain a a set of options for the theme, without any configuration modules that are usually shipped with the theme. It could contain dropdowns, radios, inputs etc. Prestashop would load it dynamically load them from the YML, present them and provide saving their values. red_circle NEED DEV POWER red_circle NEED PRODUCT TEAM

We plan to add this feature in a module, test it and contribute to the core if it works and if the community follow.
